[build]
  base = "demo"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
